### ISSUE TITLE
Erreur dans la console en retournant sur l'URL de callback

### ISSUE THREAD

**Issue by jerem-ma** [noctuelles/42-ft_transcendance#10]
Étapes pour reproduire : 
- Aller sur le site
- Cliquer sur le portail pour se connecter
- Une fois arrivé sur la page après le login, essayer de refaire le call avec le callback (c'est accessible depuis la petite flèche en haut à gauche du navigateur)

**Comment by onora-hbl** [comment]
Fix temporaire: Il est impossible de revenir sur l'URL de callback. Mais c est des catch d erreur manquant dans le back => un vrai fixe a venir
