### ISSUE TITLE
Barre de progression à 0%

### ISSUE THREAD

**Issue by onora-hbl** [noctuelles/42-ft_transcendance#110]
Quand on est à 0% d'XP, la barre de progression affiche quand meme un gros bout en bleu:
![image](https://user-images.githubusercontent.com/59887293/219122782-6a4b76d3-9fef-41b8-9966-d7e78eb11fd3.png)
Peut etre faire en sorte qui si on a 0%, on affiche pas du tout la partie bleue ?

**Comment by noctuelles** [comment]
Fix !
