### ISSUE TITLE
Nom trop grand créer un affichage bizarre

### ISSUE THREAD

**Issue by onora-hbl** [noctuelles/42-ft_transcendance#112]
Sur la liste de users du chat, si le nom est trop grand l affichage est bizarre:
![image](https://user-images.githubusercontent.com/59887293/219123558-bf13ec5e-6a3f-433a-a3a6-57bc619e865e.png)

**Comment by noctuelles** [comment]
On pourrai passer a un `flex-wrap: wrap`, mais bon ca va etre pas + beau non plus.
Une solution sale serai de limiter les characteres de l'utilisateur a 8, mais c'est hyper restrictif.

**Comment by onora-hbl** [comment]
J avoue que je réfléchissais à cette possibilité ça me parait bien 😅 8 char max c est comme un login ça se justifie
