### ISSUE TITLE
Logout si on spam refresh la page play du site

### ISSUE THREAD

**Issue by jerem-ma** [noctuelles/42-ft_transcendance#12]
Étapes pour reproduire : 
- Se connecter à transcendence
- Rester appuyer sur ctrl+R

**Comment by onora-hbl** [comment]
Je pense qu on peut pas y faire grand chose, le bug se produit car:
- En rafraichissant la page tu envoies ton refresh_token a l API qui va t en renvoyer un nouveau
- Si tu re-rafraichis pendant que la requete se fait tu vas renvoyer le meme refresh_token une 2eme fois
- Le back va repondre correctement a la premiere requete mais va envoyer une erreur a la 2eme car le meme token a été utilisé une 2ème fois. Et ducoup, comme pour le back s'est considéré comme une tentative de spoofing de token, il désactive tous les accès de l'utilisateur et attend qu'il se reconnecte
En vrai ca créer pas vraiment d'erreur pour l'utilisateur, il est juste renvoyé sur la page de login donc je vois pas trop de fix

**Comment by onora-hbl** [comment]
Finalement, fix assez simple trouvé: le refresh_token n'est invalidé qu'au bout de quelques secondes
