### ISSUE TITLE
Console errors in chat in back is dead

### ISSUE THREAD

**Issue by jerem-ma** [noctuelles/42-ft_transcendance#13]
![image](https://user-images.githubusercontent.com/59874848/212372313-f8149ec0-e221-4cf0-b2cf-6af13df53b48.png)

**Comment by onora-hbl** [comment]
L erreur en console est pas forcément grave, tant que c est catch coté front et que l utilisateur rencontre pas un comportement genant. Donc genre afficher une erreur en mode "Impossible de joindre le back" est suffisant je pense

**Comment by jerem-ma** [comment]
Ça m'a l'air complexe de ctach cette erreur. On peut pas try catch parce-que la connexion réseau se fait de manière asynchrone, et dans tous les cas, je sais même pas si c'est vraiment une bonne chose de vouloir catch cette erreur.
Au pire, ça se justifie => `The user should encounter no unhandled errors and no warnings when browsing the
website` : Tant que l'utilisateur ouvre pas la console, il verra rien :clown_face:

**Comment by onora-hbl** [comment]
J ai pas testé mais pour moi le `onError` de `useWebsocket` est la pour ca

**Comment by jerem-ma** [comment]
J'ai essayé, la fonction se déclenche bien si y'a eu une erreur, mais ça supprime pas le message dans la console (sur Firefox en tout cas)

**Comment by onora-hbl** [comment]
L erreur en console est pas grave, mais ca me parait bien de mettre un message (genre dans l infobox) pour que l utilisateur comprenne pk le site marche pas. C est du detail mais pour etre sur
