### ISSUE TITLE
Mauvais lien pour l'avatar

### ISSUE THREAD

**Issue by jerem-ma** [noctuelles/42-ft_transcendance#33]
Quand je vais sur le site, le lien pour l'avatar qui s'affiche en haut à droite, c'est celui là : `http://localhost:3000/cdn/user/dhubleur.jpg/cdn/user/jmaia.jpg`, c'est un petit peu cassé

**Comment by onora-hbl** [comment]
J arrive pas a reproduire, tu peux verifier quel lien tu as dans ta db stp ?

**Comment by jerem-ma** [comment]
Je fais ça lundi, mais en tout cas, la DB a été wipe (je crois) a un moment donné en faisant une migration et au lieu de dhubleur, il y a maintenant marqué `unknown`
J'essaie de te fournir plein de détails lundi

**Comment by jerem-ma** [comment]
PS : unknown ou autre chose, je sais plus

**Comment by noctuelles** [comment]
Vous êtes sur la DB de damien ou en local avec le container ?

**Comment by onora-hbl** [comment]
Dans ton .env du back tu as bien défini SELF_URL ? Je pense que le undefined vient de la. Une fois fait, supprimé ton compte de la db et relog toi

**Comment by jerem-ma** [comment]
C''etait bien ça du coup hoho, c'est fix :eyes:
