### ISSUE TITLE
I played against myself

### ISSUE THREAD

**Issue by noctuelles** [noctuelles/42-ft_transcendance#54]
I haven't sucessfully reproduced the bug, but i played against myself.

**Comment by onora-hbl** [comment]
Bizarre, normalement c est plus plossible. Si t as plus d infos sur comment reproduire je suis chaud

**Comment by onora-hbl** [comment]
Oh j ai reussi a l avoir, en gros faut etre en attente d un adversaire, changer d'onglet et rejoindre a nouveau. C est etrange parce que c est censé etre géré (ca n arrive d ailleurs pas si on F5 a la place de changer d onglet) mais je sais sur quoi me pencher mtn

**Comment by noctuelles** [comment]
Bien vu !!

**Comment by noctuelles** [comment]
J'ai pas réussi à reproduire avec ta procédure par contre
