### ISSUE TITLE
Message bizarre sur le profil

### ISSUE THREAD

**Issue by onora-hbl** [noctuelles/42-ft_transcendance#58]
Quand on a fait aucun matchs, sur le profil, c est ecrit "You don't have any match yet" meme si on est sur le profil de qqn d autre. Ca serait peut etre mieux de pas avoir un "YOU" ducoup mais rien de grave

**Comment by noctuelles** [comment]
Oui j'y avais pensé, mais pas rajouter...
Je vais fix ça très simplement en affichant le nom du joueur au lieu de you.
