### ISSUE TITLE
Léger scroll possible

### ISSUE THREAD

**Issue by onora-hbl** [noctuelles/42-ft_transcendance#62]
Sur toutes les pages qui ne sont pas censées être scrollables, il ya un léger scroll qui est quand même possible, certainement un petit margin qui train quelque part car c'est tjrs de la meme taille (a peu près la taille entre le haut de la page et la navbar)
Je me pencherai dessus un de ces 4 mais si qqn a une idée précise d'ou ca vient why not

**Comment by noctuelles** [comment]
En enlevant le height: 100% dans la selector `body`, ça refonctionne impec, mais tes deux boutons dans l'écran play sont cassé
