### ISSUE TITLE
Soucis d'affichage des achievements

### ISSUE THREAD

**Issue by onora-hbl** [noctuelles/42-ft_transcendance#67]
Quand les achievements ne font pas tous le meme taille on a ce genre de truc pas très beau:
![image](https://user-images.githubusercontent.com/59887293/216987113-02aff3bc-8efe-4b1c-ba27-8dfc680c61f9.png)

La progress bar est cassée sur les achievements réalisés (le `3/1` est tout a droite de l'image):
![image](https://user-images.githubusercontent.com/59887293/216987051-508e4fc2-0cc2-47f7-bad2-3c96f53dc59c.png)

**Comment by noctuelles** [comment]
Tout a fait, c'etait a cause d'un position: absolute qui n'avais pas de conteneur parent, donc qui se basais sur le body...
Pour la progress bar, c'est fix. Apres ca peut etre mieux fait les achivements ! :P
