### ISSUE TITLE
Première connection et création de compte

### ISSUE THREAD

**Issue by noctuelles** [noctuelles/42-ft_transcendance#79]
Si on crée un utilisateur "plouvel" grâce à l'adresse `http://localhost:8080/dev?name=plouvel`, et que je me connecte pour la première fois au site, je bypass complétement l'étape de création utilisateur et je me retrouve sur le profil plouvel avec la photo du robot par défaut.

Est-ce que si un utilisateur avec un vrai compte 42 par ex jmaia, crée un utilisateur avec comme username plouvel, et que moi, avec mon compte 42 en tant que plouvel, je crée mon compte, je vais avoir exactement le même bug ?

**Comment by onora-hbl** [comment]
Normalement ça devrait pas poser de soucis, c est les comptes de dev qui bypass toutes les vérifications. Je checkerai quand même pour être sur mais ça devrait pas exister dans la version finale avec la désactivation des comptes de dev

**Comment by onora-hbl** [comment]
Je confirme que ca posait pas de soucis, j ai juste ajouté un message pour avertir que le username est deja utilisé
