### ISSUE TITLE
Liste des utilisateurs ne s'update pas en temps reel

### ISSUE THREAD

**Issue by noctuelles** [noctuelles/42-ft_transcendance#83]
La liste des utilisateurs a droite du chat ne s'update pas quand un utilisateur rentre dans le channel

**Comment by noctuelles** [comment]
Le status des utilisateurs non plus.

**Comment by jerem-ma** [comment]
J'investigue 🔍

**Comment by noctuelles** [comment]
Je viens d'update ta liste d'utilsateur aussi x)

**Comment by jerem-ma** [comment]
Y'a moyen que ça soit ça le problème x)

-------- Original Message --------

**Comment by noctuelles** [comment]
Non, c'est juste des modifs du css

**Comment by jerem-ma** [comment]
Ahhh, je continue l'investigation alors

**Comment by noctuelles** [comment]
Le status ne s'update pas non plus aussi.

**Comment by jerem-ma** [comment]
Je viens de me rappeler pourquoi, ce fix est prévu, il y a un TODO dans le code que j'ai ajouté pendant un merge conflict x)
Ça sera fait

**Comment by onora-hbl** [comment]
Si jamais pour update le status il faudra que tu ecoute le ws `user-status`
