### ISSUE TITLE
La partie ne prend pas fin dans une game cree a partir du chat

### ISSUE THREAD

**Issue by noctuelles** [noctuelles/42-ft_transcendance#84]
Reproduction ->

Dans le chat, cree une partie. Dans cette partie, la detection d'utilisateur qui leave se fait mal : ca marche pour un utilisateur sur deux.

**Comment by onora-hbl** [comment]
J arrive pas a reproduire, j ai fait quitté les 2 users et les 2 sont bien détectés (c est le meme code que pour les games noramles donc je vois pas trop pk ca marcherait pas). Si t as + d infos je suis preneur

**Comment by onora-hbl** [comment]
Ah nan okay compris, c est quand le joueur qui a accepté l invite reload la page, je pense savoir d ou ca vient
