### ISSUE TITLE
Quand un utilisateur bloque un autre, en cas de MP

### ISSUE THREAD

**Issue by noctuelles** [noctuelles/42-ft_transcendance#96]
Quand un utilisateur bloque un autre dans les MP, le channel se supprime bien mais uniquement apres un reload de la page (pas en temps reel)

**Comment by noctuelles** [comment]
Je vois, il est pas supprimer mais simplement cacher jusqu'a ce que l'autre le debloque. Still, il n'y a pas d'update en temps reel.

**Comment by onora-hbl** [comment]
Ouai, je pense que je sais d'ou ca vient, je m en occupe
