### ISSUE TITLE
Impossible de supprimer, changer, le mot de passe.

### ISSUE THREAD

**Issue by noctuelles** [noctuelles/42-ft_transcendance#98]
- Quand on supprime le mot de passe, le channel passe en mode `PUBLIC`
- Seul l'operateur peut changer le mot de passe.

**Comment by onora-hbl** [comment]
T'avais pas déja fait le changement de mot de passe ? C est juste le front qui le permet pas encore nan ?

**Comment by noctuelles** [comment]
Oui le changement de mot passe c'est dans le back ! Il faut faire le front mtn.
