### ISSUE TITLE
Ban utilisateur

### ISSUE THREAD

**Issue by noctuelles** [noctuelles/42-ft_transcendance#99]
Quand un utilisateur est ban,

- Il peut pas envoyer de message, mais il devrai etre kick du channel, et ne plus pouvoir le join avant la date indique par celui qui a effectue le ban.
- Il peut encore envoyer une demande pour jouer avec les autres.
- On peut toujours promote un utilsateur ban
- On peut reban un utilisateur deja ban

**Comment by onora-hbl** [comment]
Pour tous les pts:
- Il peut encore envoyer une demande pour jouer avec les autres.
- On peut toujours promote un utilsateur ban
- On peut reban un utilisateur deja ban


Ca sera reglé par le kick. En gros actuellement notre ban est pas un kickban. Quand ca ca sera fait y aura plus rien d autres. @jerem-ma tu l avais prévu nan ?
